# Ref: https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
jobs:
  build:
    working_directory: ~/ayzer
    docker:
      - image: circleci/node:7.10.0-browsers
    steps:
      - checkout
      - restore_cache:
          key: ayzer-{{ .Branch }}-{{ checksum "./ayzer-workspace/package.json" }}
      - run:
          name: Install Chromedriver latest version
          command: |
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update
            sudo apt-get install google-chrome-stable

      - run:
          name: "Install dependencies"
          command: |
            cd ayzer-workspace
            node --version
            npm --version
            npm install --quiet

      - save_cache:
          key: ayzer-{{ .Branch }}-{{ checksum "./ayzer-workspace/package.json" }}
          paths:
            - "node_modules"
      - run: cd ayzer-workspace; xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNoSandbox
      - run: cd ayzer-workspace; xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js