# Ref: https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
jobs:
  build:
    working_directory: ~/ayzer
    docker:
      - image: circleci/node:7.10.0-browsers
    steps:
      - checkout
      - restore_cache:
          key: ayzer-{{ .Branch }}-{{ checksum "./ayzer-app/package.json" }}
      - run: cd ayzer-app; npm install
      - save_cache:
          key: ayzer-{{ .Branch }}-{{ checksum "./ayzer-app/package.json" }}
          paths:
            - "node_modules"
      - run: cd ayzer-app; xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNoSandbox
      - run: cd ayzer-app; xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js