# Ref: https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
jobs:
  build:
    working_directory: ~/ayzer
    docker:
      - image: circleci/node:7.10.0-browsers
    steps:
      - checkout
      - restore_cache:
          key: ayzer-{{ .Branch }}-{{ checksum "./ayzer-workspace/package.json" }}
      - run:
          name: Install Chromedriver latest version
          command: |
            sudo apt-get update
            sudo apt-get install lsb-release
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            sudo sed -i ‘s|HERE/chrome"|HERE/chrome" --disable-setuid-sandbox|g’ /opt/google/chrome/google-chrome
            rm google-chrome.deb
      - run:
          name: "Install dependencies"
          command: |
            cd ayzer-workspace
            node --version
            npm --version
            npm install --quiet

      - save_cache:
          key: ayzer-{{ .Branch }}-{{ checksum "./ayzer-workspace/package.json" }}
          paths:
            - "node_modules"
      - run: cd ayzer-workspace; xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNoSandbox
      - run: cd ayzer-workspace; xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js